language: generic
sudo: required
services: 
 - docker

before_install:
 - docker build -t g1git/react-test -f ./client/Dockerfile.dev ./client

script:
 - docker run -e CI=true g1git/react-test npm test
 
after_success:
 - docker build -t g1git/multi-client -f ./client/ 
 - docker build -t g1git/multi-server -f ./server/ 
 - docker build -t g1git/multi-worker -f ./worker/ 
 - docker build -t g1git/multi-nginx -f ./nginx/ 
 
 # login into docker
 - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
 # push build to dockerhu
 - docker push g1git/multi-client
 - docker push g1git/multi-server
 - docker push g1git/multi-worker
 - docker push g1git/multi-nginx

deploy:
 provider: elasticbeanstalk
 region: "us-east-2"
 app: "multi-docker"
 env: "MultiDocker-env"
 bucket_name: "elasticbeanstalk-us-east-2-326198890687"
 bucket_path: "multi-docker"
 on:
   branch: master
 access_key_id:  $AWS_ACCESS_KEY
 secret_access_key: $AWS_SECRET_KEY